### ISSUE TITLE
Unmet peer dependency

### ISSUE THREAD

**Issue by dustinfarris** [mattkrick/cashay-schema-loader#4]
I want to hijack some of the code here for a non-webpack [Ember/Cashay integration](https://github.com/mattkrick/cashay/issues/120) I'm working on.  package.json specifies webpack as a peer dependency which I would rather not be required for what I'm doing.

**Comment by dustinfarris** [comment]
@mattkrick what are your thoughts on using this as repo as a toolbelt for non-webpack integrations?  Is that changing the scope here inappropriately?  Would it be better form for me to create a similar Ember-specific "loader" repo (essentially copy+pasting everything here, but with Ember scaffolding)?

**Comment by mattkrick** [comment]
Oh yeah, i would definitely avoid any work on this repo, it's just a bunch of dead code. I originally planned to break out the webpack loader as a separate npm package, but realized it was so much cleaner just doing it inside cashay, plus if you use tree-shaking accordingly, it won't increase the client payload. The code inside `cashay/schema` is more up to date.

**Comment by dustinfarris** [comment]
Great, thanks.
